### ISSUE TITLE
Display <f:grLine>, <f:grBrace>

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen#14]
From https://faustedition.uni-wuerzburg.de/wiki/index.php/KW_42_2015

Test cases:
* http://dev.faustedition.net/documentViewer?faustUri=faust://xml/document/test/test.xml&page=12&view=facsimile_document
* http://dev.faustedition.net/documentViewer?faustUri=faust://xml/document/test/test.xml&page=13&view=facsimile_document
* http://dev.faustedition.net/documentViewer?faustUri=faust://xml/document/test/test.xml&page=14&view=facsimile_document
* http://dev.faustedition.net/documentViewer?faustUri=faust://xml/document/test/test.xml&page=15&view=facsimile_document

**Comment by gerritbruening** [comment]
At the latest meeting the idea of generic substitutes came up again.

**Comment by thvitt** [comment]
Looks (also from the network trace) as if neither Firefox nor Chrome follow svg:use directives that point to external URLs, at least the graphical element isn't loaded.

So maybe postprocess and inline this? @wissenbach, are the included graphics required for the layout process?

**Comment by thvitt** [comment]
Alternatively, we could maybe add a static `<defs>` with the 7 graphical elements to every page – they aren't _that_ large

**Comment by wissenbach** [comment]
@thvitt, the immediate problem seems to be that the svg:use directive is not successful when the pre-generated svg is loaded into the browser (e.g. in http://dev.faustedition.net/documentViewer?faustUri=faust://xml/document/test/test.xml&page=12&view=facsimile_document)

Another issue is whether it is loaded at generation time. I think the layout process should also work without it being loaded. Notice the gap between "filling a gap ... inside a line" in the above link (where there should be the graphic), so I think the layout stage is fine. When I generate locally via debug.html, the svg:use directive works as expected with graphics visible.

Maybe something about the way the svg gets included into the dom via js? Network trace says indeed that the browser never attempts to load the svg:used files...

**Comment by wissenbach** [comment]
ge:used is affected as well, see

http://dev.faustedition.net/documentViewer?faustUri=faust://xml/document/test/test.xml&page=18&view=facsimile_document.
