### ISSUE TITLE
SlimerJS/Firefox based rendering for diplomatic transcripts?

### ISSUE THREAD

**Issue by thvitt** [faustedition/faust-gen#19]
In c6e92c0 ff. habe ich versucht, die Generierung der SVGs für die diplomatische Umschrift von PhantomJS auf SlimerJS umzustellen – u.a. wegen #13. Nach ein paar Fehlern (s.a. #17) ist dabei ein Rendering herausgekommen, das deutliche Unterschiede im vertikalen Spacing zwischen den beiden zeigt. Die folgende Darstellung ist aus Screenshots von [2 H, S. 67](http://beta.faustedition.net/documentViewer?faustUri=faust://xml/document/faust/2/gsa_391098.xml&page=67&view=facsimile_document) beider Varianten montiert, aligniert an der Grundlinie der Zeile „Ihm wird kein Raum für ſeine Poſſen bleiben“:

![PhantomJS- vs. SlimerJS-basiertes Rendering](https://cloud.githubusercontent.com/assets/1906208/19771765/51cf15e0-9c64-11e6-9c7d-eefef2cf76a5.png)

Leider gibt es auch fehlende Elemente: Mindestens die grafischen Elemente (hier: vertikale Linien) fehlen in der SlimerJS-Darstellung (und es ist noch zu prüfen warum und wie sich das beheben lässt).

Für das weitere Vorgehen und die Entscheidung für eine Rendering-Engine müsste u.a. geklärt werden:
1. Ist das SlimerJS-Layout so jetzt besser? (abgesehen von den fehlenden Linien)
2. Gibt es noch weitere Fehler oder unerwünschte Abweichungen im SlimerJS-Layout?
3. Gibt es noch unerwünschte _horizontale_ Skalierungsprobleme, die einen spürbaren negativen Effekt auf die Darstellung haben?

**Comment by wissenbach** [comment]
Der vertikalen Zeilenabstand könnte unabhängig (bzw. gerade abhängig?) von der verwendeten Engine angepasst werden, das sollte also nicht das entscheidende Kriterium für die Auswahl sein.

**Comment by wissenbach** [comment]
siehe auch https://github.com/faustedition/faust-web/issues/22

**Comment by thvitt** [comment]
Es bleibt jetzt bei der puppetteer-Lösung, auch weil ich damit mittlerweile noch mehr mache (PDFs und so)
