### ISSUE TITLE
Implement missing representations of <g>-elements

### ISSUE THREAD

**Issue by wissenbach** [faustedition/faust-gen#2]
Insert missing graphs for <g>-elements according to the attached table.

[g-mapping.xlsx](https://github.com/faustedition/faust-gen/files/25075/g-mapping.xlsx)

Issue copied from https://faustedition.uni-wuerzburg.de/wiki/index.php/KW_42_2015

**Comment by wissenbach** [comment]
Test cases:
* https://faustedition.uni-wuerzburg.de/xml/transcript/test/12.xml
* https://faustedition.uni-wuerzburg.de/xml/transcript/test/16.xml
* https://faustedition.uni-wuerzburg.de/xml/transcript/test/17.xml
* https://faustedition.uni-wuerzburg.de/xml/transcript/test/18.xml

**Comment by gerritbruening** [comment]
The following list is more up to date than g-mapping.xlsx:
https://faustedition.uni-wuerzburg.de/wiki/index.php/Benutzer:Vitt

**Comment by wissenbach** [comment]
Why not use preliminary unicode characters for the glyphs we don't have yet? The closest possible, so a normal + for #g_transp_4 etc. Alternatives are to display placeholder � or nothing at all. Which one?

**Comment by wissenbach** [comment]
This is fixed by the following commit in dependency faust-app
https://github.com/faustedition/faust-app/commit/3f112a7554f767364b6cbec463e39daef8ccab62
The table in 
https://github.com/faustedition/faust-app/blob/master/faust/src/main/java/de/faustedition/transcript/input/GXMLTransformerModule.java
contains the mappings.

**Comment by gerritbruening** [comment]
As for the +, see https://github.com/faustedition/faust-app/commit/6acdc26735ee8853846d0f851947d722ddc516be

**Comment by gerritbruening** [comment]
@wissenbach , I think this is closed, isn't it?
