### ISSUE TITLE
choice/(abbr|expan)

### ISSUE THREAD

**Issue by thvitt** [faustedition/faust-gen#20]
In [1 H.11 S. 13](http://dev.faustedition.net/documentViewer?faustUri=faust://xml/document/archival/sb_berlin/Nachl_Herder_XXXII-5.xml&page=13&view=facsimile_document) gibt es zahlreiche abbr/expan-Paare (Me/Mein, Hz/Herz …), die einfach nebeneinander gerendert werden. 

Ist das so intendiert? Gibt es eine bessere Lösung?

**Comment by gerritbruening** [comment]
Nein, bestimmt nicht!

**Comment by gerritbruening** [comment]
In beta seh ichs nicht, die dev wird auf meinem Handy nicht angezeigt. (Windows Phone, wie IE)

**Comment by thvitt** [comment]
Intressant. Dann ist das eine Regression

**Comment by wissenbach** [comment]
Ist das durch ein update 2.2.0-SNAPSHOT kaputt gegangen? Was wird in der aktuellen beta.faustedition.net verwendet, auch 2.2.0-SNAPSHOT?

**Comment by thvitt** [comment]
beta.faustedition.net verwendet auch 2.2.0-SNAPSHOT. Habe allerdings mittlerweile gesehen,d ass in der beta die [Debug-Seite](http://beta.faustedition.net/debug?faustUri=faust://xml/document/archival/sb_berlin/Nachl_Herder_XXXII-5.xml&page=13&view=facsimile_document) auch in Firefox korrekt rendert, während sie das für die dev nicht tut, so dass wohl meine Stümpereien ursächlich waren und nicht der Renderer. Ich werde das mal bisecten und mich dann ggf. melden.

(PhantomJS 2.2.0-SNAPSHOT hat noch das nervige Problem (#17), dass es nichtdeterministisch bei bestimmten Seiten crasht, wie man [gegen Ende von Buildlog 102](http://dev.digital-humanities.de/ci/job/faust-gen/102/console) gut sehen kann – das Javaprogramm versucht Seiten, bei denen der Renderer gecrasht hat, solange neu zu rendern, bis sich die Zahl crashender Seiten nicht mehr verringert hat)

**Comment by thvitt** [comment]
Macht natürlich Sinn, dass es 6eab6cb5f600be9ee941263daec3ac6a49face08 war, mit dem ich versucht habe, ein paar crashes zu heilen, ohne wirklich zu verstehen, was ich da tue. Reverte den mal selektiv …

**Comment by wissenbach** [comment]
Da fällt mir ein... #21
