### ISSUE TITLE
Reconsider f:overw and rend="inbetween" rendering

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen#25]
I wonder whether it would make things easier if we abandon the current practice of rendering f:overw and `seg rend="inbetween"`. I see two reasons for this:
1. sub and superscript are not rendered in firefox (due to firefox, not to the SVG, but this seems permanent)
2. sub and superscript rendering may cause trouble with regard to line spacing. Or do think that this is fixed with your recent reworking of the linespace, @wissenbach ?
3. A side effect of (2) is that vertical alignment is distorted by the greater height of lines. See, for example, [H P99.2](http://beta.faustedition.net/documentViewer.php?faustUri=faust://xml/document/faust/2.2/gsa_390873.xml&page=1&view=document) or [2 III H.2:2, p. 9](http://beta.faustedition.net/documentViewer.php?faustUri=faust://xml/document/faust/2.3/gsa_390825.xml&page=9&view=document).

Maybe it is less complicated to search for an alternative solution , e.g. small for `f:under` and bold for `f:over` and `seg rend="inbetween"`.

However, it is not my intention to rock the boat! If you, Moritz, think that the current solution is preferable, just ignore these remarks.

**Comment by gerritbruening** [comment]
Part of https://github.com/faustedition/faust-gen/issues/5.

**Comment by gerritbruening** [comment]
See also https://github.com/faustedition/faust-web/commit/4aa7888118f748faf53ecced501844920cada4c4.

Now fixed, isn't it, @wissenbach?

**Comment by wissenbach** [comment]
Yes, fixed by bolding instead of sub-/superscript as suggested above.
