### ISSUE TITLE
Lines placed on top of each other when graphical elements are involved

### ISSUE THREAD

**Issue by wissenbach** [faustedition/faust-gen#31]
The fix for #5 causes problems when there are lines that only contain a graphical element such as a graphical line. The following lines or interlines are written over each other. Used-markers are not displayed either.

**Comment by wissenbach** [comment]
@gerritbruening can you remember the example that shows this? Can it be worked into the test data set?

**Comment by gerritbruening** [comment]
Thanks for reminding me. The problem occured in the following ms: http://dev.faustedition.net/documentViewer?faustUri=faust://xml/document/faust/2.3/gsa_391362.xml&page=3&view=document.
I have added the line 
`<ge:line rend="centered" type="inter" xml:id="line"><handShift new="#g_bl"/><f:grLine f:orient="horiz" f:style="linear"/></ge:line>`
as is in the Testhandschrift p. 5.
