### ISSUE TITLE
ge:used is lost

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen#32]
When I compare the beta and the dev, it seems that the rendering of `ge:used` is lost. Is this a known bug?

For an example, see http://dev.faustedition.net/documentViewer?faustUri=faust://xml/document/test/test.xml&page=18&view=facsimile_document.

**Comment by thvitt** [comment]
same problem as #14

**Comment by wissenbach** [comment]
duplicate of #14
