### ISSUE TITLE
Table states multiple xml-sources

### ISSUE THREAD

**Issue by sandrakrause** [faustedition/faust-gen#35]
The column "Auszug" in http://dev.faustedition.net/archive_testimonies shows an error massage that claims that there are multiple xml-sources for one testimony.
e.g. Gräf-No. 1711. Source is Biedermann (1), Bd. 7, S. 107. Error shows "4 XML-Quellen: graef_1711, graef_1718, graef_1719, graef_1721"
Problem is:
The xml does contain all of these four xml-sources, but they shouldn't all be referenced to the same testimony. There shouldn't be an issue with multiple IDs in one document, as long as they don't refer to the same section.
It's irritating because some IDs are affected and others aren't.
e.g. the Source Biedermann (1), Bd. 7 does contain Gräf 1705 as well, but it's not affected by that issue.

**Comment by thvitt** [comment]
The part of the transformation that creates these messages probably has not yet been adapted to the concept of one HTML file per testimony. 

The files are there with URLs like http://dev.faustedition.net/testimony/graef_1711 – the code in testimony-table.xls probably just needs to be simplified.

**Comment by thvitt** [comment]
(→ should be a faust-gen-html issue)
