### ISSUE TITLE
f:grLine seems to ascend a bit

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen#39]
Test case:
http://dev.faustedition.net/documentViewer?faustUri=faust://xml/document/test/test.xml&page=12&view=facsimile_document

![grafik](https://user-images.githubusercontent.com/10358005/35501889-8e6de158-04db-11e8-9740-0e11e906cbd8.png)

Is this intended or not? Or is this mysterious and therefore hard to fix? In this case, feel free to add the wontfix label.

**Comment by wissenbach** [comment]
fixed by https://github.com/faustedition/faust-web/commit/ce01b324c61e9dd235771c4f4e1612ebb32c61d7
