### ISSUE TITLE
Overlays shifted south

### ISSUE THREAD

**Issue by thvitt** [faustedition/faust-gen#45]
While the overlay lines covered the corresponding lines in the facsimile in the beta version ([example from 2 H S.5 / beta](http://beta.faustedition.net/documentViewer?faustUri=faust://xml/document/faust/2/gsa_391098.xml&page=5&view=facsimile)),
![Excerpt from beta](https://user-images.githubusercontent.com/1906208/42627777-50041ac6-85ce-11e8-8bd3-4b20d6fbaf21.png)

… they are shifted downwards in very recent versions of the dev version ([same example, 2 H S.5 / dev](http://dev.faustedition.net/document?sigil=2_H&page=5&view=facsimile)):
![Excerpt from dev](https://user-images.githubusercontent.com/1906208/42627877-9b0b24ce-85ce-11e8-9c18-92e58935a1d3.png)

Can this be a regression caused by your recent work on the rendering, @wissenbach? 

(I actually like the shifted version better in this quite clean example …)

**Comment by wissenbach** [comment]
Yes, this is an side-effect of 34e5ea4ed012a407b005d78c0a9b05385645d2fb, which i have reversed.
