### ISSUE TITLE
Zeichen tief und hoch

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen#47]
Es ging um Stellen, die bei mir so aussehen:

![grafik](https://user-images.githubusercontent.com/10358005/46357467-364fdc00-c665-11e8-966e-7642ec49004e.png)
 
(http://dev.faustedition.net/document?sigil=1_H.5&page=3&view=facsimile_document, Firefox; Chrome identisch)

Dahinter stecken, in Reihenfolge des Auftauchens, f:under, f:over, seg rend="inbetween".
Ist das so gedacht? Solche Dinge waren mal umgekehrt tief- und hochgestellt, dann seit einiger Zeit nicht mehr, aber nicht so herum.

Ich könnte mir vorstellen, dass das an dem schönen Fix von #30 liegen könnte?

**Comment by wissenbach** [comment]
Ja, dieses Problem ist ein unerwünschter Nebeneffekt des Fixes zu #30, deswegen mache ich den Fix rückgängig. D.h. aber, dass #30 weiterhin ein Problem ist.

**Comment by gerritbruening** [comment]
OK, danke für den revert!
