### ISSUE TITLE
Equalise line spacing

### ISSUE THREAD

**Issue by wissenbach** [faustedition/faust-gen#5]
- Reduce line spacing of interlines.
- Equalise spacing of lines with overwrites

Example:  http://beta.faustedition.net/documentViewer.php?faustUri=faust://xml/document/faust/2.3/gsa_391347.xml&page=5&view=document

Issue copied from https://faustedition.uni-wuerzburg.de/wiki/index.php/KW_42_2015

**Comment by gerritbruening** [comment]
Test cases:
* http://dev.faustedition.net/documentViewer?faustUri=faust://xml/document/test/test.xml&page=19&view=facsimile_document (over)

**Comment by gerritbruening** [comment]
`ge:rewrite` seems to cause a greater linespread (e.g. [2 H, S. 10 "Wechseldauer"](http://dev.faustedition.net/documentViewer?faustUri=faust://xml/document/faust/2/gsa_391098.xml&page=10&view=document)).
