### ISSUE TITLE
Implement string substitution for ligatures etc.

### ISSUE THREAD

**Issue by wissenbach** [faustedition/faust-gen#6]
ſs -> ß etc. 

Please supply an extensive list!

Issue taken from https://faustedition.uni-wuerzburg.de/wiki/index.php/KW_42_2015

**Comment by gerritbruening** [comment]
Forgot that this is only relevant for the rendering of "last stages". To them, the following two rules apply:
ſs -> ß
sſ with parent::tei:orig -> ß

**Comment by gerritbruening** [comment]
Discussed the issue with Dietmar, decided to retain all Ae etc. als well as a instead of ä. See https://github.com/faustedition/faust-web/commit/4e6a458acd5b2272bd219c6cec73943f13b4b1e3

**Comment by gerritbruening** [comment]
In the end, the following two rules apply for the "last stage":
ſs -> ß
sſ with parent::tei:orig -> ß

(otherwise ſs and the sſ with parent::tei:orig would wrongly be rendered as ss)
