### ISSUE TITLE
Dependency and build management

### ISSUE THREAD

**Issue by wissenbach** [faustedition/faust-gen#8]
The dependency https://github.com/faustedition/faust-app is in the VCS as binaries in https://github.com/faustedition/faust-gen/blob/master/svg_rendering/java/

If I update something in the dependency, should I just compile it and always upload the binaries to VCS? Or upload it to http://dev.digital-humanities.de/nexus/ , etc.?

**Comment by thvitt** [comment]
Uploading the binaries to VCS would be great. At least until I've implemented a way to integrate the build steps from the various projects, but that's low-priority now.

**Comment by wissenbach** [comment]
Ok, I'll do that and close this issue for now.
